### PR TITLE
Set to new Tools endorser in sandbox

### PR DESCRIPTION
**Pull request by loneil**
Use the new Endorser in the Tools repo. Set the 'quick connect' flag.

### CODE REVIEW

**Comment by loneil** [comment]
@esune realized I'm not clear on whether this takes the latest code from Traction repo `main` when a build is triggered? Or does it need a release in Traction?

The new Endorser UI and quick connect stuff won't apply unless the new code is in place (but everything should still work either way or the other)

**Comment by WadeBarnes** [comment]
> Also I can't request a reviewer on this repo.

@loneil, you should be able to now.

**Review by WadeBarnes — APPROVED** [review]
LGTM, but I'm not familiar with the DID.  So I'll defer to someone else to verify that.

**Review by esune — APPROVED** [review]

**Comment by esune** [comment]
> @esune realized I'm not clear on whether this takes the latest code from Traction repo `main` when a build is triggered? Or does it need a release in Traction?
> 
> The new Endorser UI and quick connect stuff won't apply unless the new code is in place (but everything should still work either way or the other)
> 
> Also I can't request a reviewer on this repo.

This works off of the latest released code

**Pull request merged**
