### PR TITLE
adding rocket.chat notification to gha workflow

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Comment by WadeBarnes** [comment]
This is the continuation of https://github.com/bcgov/trust-over-ip-configurations/pull/152

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@rajpalc7, can you update the PR and commit descriptions to more accurately reflect the changes.  You are not adding the file, you are adding rocket.chat notification to the workflow.

Also this revision is missing the changes you made and I reviewed this morning.

**Comment by rajpalc7** [comment]
thanks @WadeBarnes changes made accordingly

**Comment by WadeBarnes** [comment]
Just the PR description left to fix; 
image

**Comment by rajpalc7** [comment]
@WadeBarnes  fixed now :)

**Comment by WadeBarnes** [comment]
fixes: https://github.com/bcgov/trust-over-ip-configurations/issues/156, https://github.com/bcgov/DITP-DevOps/issues/128

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
