### PR TITLE
Update issuer-agent build to include DRPC plug-in

### PR DESCRIPTION
**Pull request by esune**
Base image version could be one minor lower (`0.12.1`), however I do not think it would be beneficial to start with an older release since agents wanting to use the protocol will need to be updated any way.

Build/deployments have not yet been updated: @WadeBarnes I will want to sync-up with you if I work on those as I know there's a versioning pattern that needs to be respected.

### CODE REVIEW

**Review by WadeBarnes — APPROVED** [review]

**Review by WadeBarnes — APPROVED** [review]

**Comment by esune** [comment]
@WadeBarnes I added the startup parameter I was missing to enable the plugin in ACA-Py. I was debating on whether to make this a configurable setting, however I think that it would be adding unnecessary complexity for something like this so went with the "always on" type of approach.

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
I'd recommend going with environment variable form of activating the plugin.  That way it's easier to turn plugins on and off.

Example:
- https://github.com/bcgov/openshift-aries-mediator-service/blob/17643eee553e83030e9034ea48d86716ca168b0b/openshift/templates/aries-mediator-agent/aries-mediator-agent-deploy.yaml#L286-L289
- https://github.com/bcgov/openshift-aries-mediator-service/blob/17643eee553e83030e9034ea48d86716ca168b0b/openshift/templates/aries-mediator-agent/aries-mediator-agent-deploy.dev.param#L51-L52


Pro-Tip:
- Though you can specify `ACAPY_PLUGIN` in string format, `ACAPY_PLUGIN=a-single-plugin`, when you only have a single plugin, you should always use list format which works for one or more plugins; for example:
  - `ACAPY_PLUGIN=[plugin-1]`
  - `ACAPY_PLUGIN=[plugin-1,plugin-2]`
  - `ACAPY_PLUGIN=[plugin-1,plugin-2,plugin-3, ... plugin-n]`

**Comment by esune** [comment]
@WadeBarnes thanks for the tip, updated the PR with the appropriate changes.

I only updated the param files for the IDIM agents since I am not aware of other agents requiring this, and because there are profiles that are now outdated/unused (should we prune them?). We can update other profiles as we go through them.

**Comment by WadeBarnes** [comment]
> I only updated the param files for the IDIM agents since I am not aware of other agents requiring this, and because there are profiles that are now outdated/unused (should we prune them?). We can update other profiles as we go through them.

Yes, we should prune the one's we've decommissioned.

**Comment by esune** [comment]
> > I only updated the param files for the IDIM agents since I am not aware of other agents requiring this, and because there are profiles that are now outdated/unused (should we prune them?). We can update other profiles as we go through them.
> 
> Yes, we should prune the one's we've decommissioned.

👍🏻 - it will be in a separate PR as there likely are several profiles that need reviewing/auditing.

**Review by WadeBarnes — APPROVED** [review]

**Pull request merged**
