### PR TITLE
Migrate agents from Indy/Askar to Askar only ACA-Py images

### PR DESCRIPTION
**Pull request by WadeBarnes**
This PR updates the `issuer-agent` configurations to support the Askar only ACA-Py images

### CODE REVIEW

**Comment by WadeBarnes** [comment]
The configuration upgrades for the `idim` profiles have been deployed to all environments and tested.  LSBC `dev` have been migrated to Askar storage, but has not yet been migrated to the Askar only image and configuration.

**Comment by WadeBarnes** [comment]
Ready for review.  The configuration updates have been deployed and tested in `dev` and `test`.

**Comment by WadeBarnes** [comment]
Included @i5okie and @rajpalc7 on the review as an FYI.

**Review by i5okie — APPROVED** [review]
lgtm

**Comment by rajpalc7** [comment]
looks good wade

**Review by rajpalc7 — APPROVED** [review]

**Review by esune — APPROVED** [review]

**Pull request merged**
