### PR TITLE
Use DITP hosted ledgers in TEST traction env

### PR DESCRIPTION
**Pull request by loneil**
Set the ledgers.yml for the hosted ledgers.

### CODE REVIEW

**Review by esune — DISMISSED** [review]

**Review by esune — COMMENTED** [review]
Actually, do we want the `dev` endorser in the `test` environment? We should probably only target `test` ledgers

**Comment by loneil** [comment]
We don't need it, it's there in the default values for all envs, but if the intent is to use a single ledger here we can just have bcovrin-test

**Comment by esune** [comment]
I would ideally want the Traction instances to be "aligned" with the ledger instances: `dev` Traction to `dev` ledgers, etc.

Thinking about it, we will have a couple of other options going forward for each environment:
- We will connect also to the CANdy endorsers
- We will connect also to the Sovrin endorsers
- CANdy dev is supported by the BC wallet, so we won't need to have `test` in `dev`, etc.

Can we maybe add the CANdy endorsers and keep the environments "aligned" from now on? Thoughts?

**Comment by swcurran** [comment]
In picking the ledgers, you should make sure that the BC Wallet supports all of them.  No sense in using a ledger that BC Wallet doesn’t support.

**Comment by loneil** [comment]
Changed to just bcovrin-test for now in this env.

**Review by esune — APPROVED** [review]

**Pull request merged**
